export const localizations = {
  error: {
    request: "Error al hacer la peticion",
    notFound: "No se encontro la informacion",
    server: "Error del servidor",
    unknown: "Error desconocido",
    login: "Error al iniciar sesión",
    createUser: "Error al crear usuario",
  },
  validation: {
    emailRequired: "El correo electrónico es requerido",
    emailInvalid: "El correo electrónico no es válido",
    passwordRequired: "La contraseña es requerida",
    passwordMinLength: "La contraseña debe tener al menos 6 caracteres",
  },
  login: {
    title: "Iniciar sesión",
    email: "Correo Electronico",
    password: "Contraseña",
    submit: "Iniciar sesión",
  },
  success: {
    login: "Inicio de sesión exitoso",
  },
  register: {
    success: "Usuario creado exitosamente",
    error: "Error al crear usuario",
    name: "Nombre",
    lastName: "Apellido",
    email: "Correo Electronico",
    password: "Contraseña",
    roleId: "Rol",
    warehouses: "Bodega",
  },
  inventory: {
    title: "Registro de Inventario",
    countId: "Conteo",
    cutoffDate: "Fecha de Corte",
    warehouseId: "Bodega",
    productId: "Producto",
    quantityInPackaging: "Cantidad (Unidad de Empaque)",
    quantityInUnits: "Cantidad (Unidades)",
    createdAt: "Fecha y Hora de Creación",
    selectCount: "Seleccione un conteo",
    selectWarehouse: "Seleccione una bodega",
    selectProduct: "Seleccione un producto",
    createSuccess: "Registro de inventario creado exitosamente",
    createError: "Error al crear registro de inventario",
    createButton: "Crear Registro",
    creating: "Creando...",
  }
};